#TARGET = iphone:5.1
include theos/makefiles/common.mk

APPLICATION_NAME = IntrospyTestApp
IntrospyTestApp_FILES = main.m IntrospyTestAppApplication.mm RootViewController.mm DataStorageTester.m
IntrospyTestApp_FRAMEWORKS = UIKit CoreGraphics Security

include $(THEOS_MAKE_PATH)/application.mk
